instruction = 0
func_dec = 1
func_or_var_dec = 2
aux_func_or_var_dec = 3
aux_add_dec = 4
aux_var_asign = 5
while_op = 6 # opcional
conditions = 7
bool_logic_conn = 8
bool_logic = 9
logic_conn = 10
operation = 11
aux_operation = 12
scanf = 13 #opcional
printf = 14 
aux_printf = 15
add_mods = 16
aux_mods = 17
add_ids = 18
aux_ids = 19
datatype = 20
data = 21
func_header = 22
func_call = 23
func_call_or_dec_aux = 24
func_call_or_dec = 25
vasign_func_call = 26
func_instruction = 27
if_else = 28
if_dec = 29
else_dec = 30
ifelse_bool =31
ifelse_conditions = 32
ifelse_bool_logic_conn = 33
ifelse_bool_logic = 34

table = [
    # 0
    [instruction, 'SEMICOLON', None],
    [instruction, 'COMMA', None],
    [instruction, 'WHILE', None],
    [instruction, 'LPAREN', None],
    [instruction, 'RPAREN', None],
    [instruction, 'LBRACE', None],
    [instruction, 'RBRACE', None],
    [instruction, 'READ', None],
    [instruction, 'QUOTES', None],
    [instruction, 'WRITE', None],
    [instruction, 'BOOL', None],
    [instruction, 'LOGIC', None],
    [instruction, 'ASSIGN', None],
    [instruction, 'INT', [func_or_var_dec, instruction]],
    [instruction, 'FLOAT', [func_or_var_dec, instruction]],
    [instruction, 'CHAR', [func_or_var_dec, instruction]],
    [instruction, 'RELATIONAL', None],
    [instruction, 'OP', None],
    [instruction, 'MOD', None],
    [instruction, 'ID', ['ID', vasign_func_call, 'SEMICOLON', instruction]],
    [instruction, 'STRING', None],
    [instruction, 'NUMBER', None],
    [instruction, 'RETURN', None],
    [instruction, 'IF',None ],
    [instruction, 'ELSE', None],
    [instruction, 'EOF', None],

    #1
    [func_instruction, 'SEMICOLON', None],
    [func_instruction, 'COMMA', None],
    [func_instruction, 'WHILE', [while_op, func_instruction]],
    [func_instruction, 'LPAREN', None],
    [func_instruction, 'RPAREN', None],
    [func_instruction, 'LBRACE', None],
    [func_instruction, 'RBRACE', ['empty']],
    [func_instruction, 'READ', [scanf, 'SEMICOLON', func_instruction]],
    [func_instruction, 'QUOTES', None],
    [func_instruction, 'WRITE', [printf, 'SEMICOLON', func_instruction]],
    [func_instruction, 'BOOL', None],
    [func_instruction, 'LOGIC', None],
    [func_instruction, 'ASSIGN', None],
    [func_instruction, 'INT', [func_or_var_dec, func_instruction]],
    [func_instruction, 'FLOAT', [func_or_var_dec, func_instruction]],
    [func_instruction, 'CHAR', [func_or_var_dec, func_instruction]],
    [func_instruction, 'RELATIONAL', None],
    [func_instruction, 'OP', None],
    [func_instruction, 'MOD', None],
    [func_instruction, 'ID', ['ID', vasign_func_call, 'SEMICOLON', func_instruction]],
    [func_instruction, 'STRING', None],
    [func_instruction, 'NUMBER', None],
    [func_instruction, 'RETURN', ['RETURN', data, 'SEMICOLON']],
    [func_instruction, 'IF', [if_else, func_instruction]],
    [func_instruction, 'ELSE', [if_else, func_instruction]],
    [func_instruction, 'EOF', [if_else, func_instruction]],
    
    [func_dec, 'SEMICOLON', None],
    [func_dec, 'COMMA', None],
    [func_dec, 'WHILE', None],
    [func_dec, 'LPAREN', None],
    [func_dec, 'RPAREN', None],
    [func_dec, 'LBRACE', ['LBRACE', instruction, 'RBRACE']],
    [func_dec, 'RBRACE', None],
    [func_dec, 'READ', None],
    [func_dec, 'QUOTES', None],
    [func_dec, 'WRITE', None],
    [func_dec, 'BOOL', None],
    [func_dec, 'LOGIC', None],
    [func_dec, 'ASSIGN', None],
    [func_dec, 'INT', None],
    [func_dec, 'FLOAT', None],
    [func_dec, 'CHAR', None],
    [func_dec, 'RELATIONAL', None],
    [func_dec, 'OP', None],
    [func_dec, 'MOD', None],
    [func_dec, 'ID', None],
    [func_dec, 'STRING', None],
    [func_dec, 'NUMBER', None],
    [func_dec, 'IF',None ],
    [func_dec, 'ELSE', None],
    [func_dec, 'EOF', None],

    [func_call_or_dec_aux, 'SEMICOLON', None],
    [func_call_or_dec_aux, 'COMMA', None],
    [func_call_or_dec_aux, 'WHILE', None],
    [func_call_or_dec_aux, 'LPAREN', None],
    [func_call_or_dec_aux, 'RPAREN', ['RPAREN', func_call_or_dec]],
    [func_call_or_dec_aux, 'LBRACE', None],
    [func_call_or_dec_aux, 'RBRACE', None],
    [func_call_or_dec_aux, 'READ', None],
    [func_call_or_dec_aux, 'QUOTES', None],
    [func_call_or_dec_aux, 'WRITE', None],
    [func_call_or_dec_aux, 'BOOL', None],
    [func_call_or_dec_aux, 'LOGIC', None],
    [func_call_or_dec_aux, 'ASSIGN', None],
    [func_call_or_dec_aux, 'INT', None],
    [func_call_or_dec_aux, 'FLOAT', None],
    [func_call_or_dec_aux, 'CHAR', None],
    [func_call_or_dec_aux, 'RELATIONAL', None],
    [func_call_or_dec_aux, 'OP', None],
    [func_call_or_dec_aux, 'MOD', None],
    [func_call_or_dec_aux, 'ID', ['ID', 'RPAREN', func_call_or_dec]],
    [func_call_or_dec_aux, 'STRING', None],
    [func_call_or_dec_aux, 'NUMBER', None],
    [func_call_or_dec_aux, 'IF',None ],
    [func_call_or_dec_aux, 'ELSE', None],
    [func_call_or_dec_aux, 'EOF', None],

    [vasign_func_call, 'SEMICOLON', None],
    [vasign_func_call, 'COMMA', None],
    [vasign_func_call, 'WHILE', None],
    [vasign_func_call, 'LPAREN', ['LPAREN', 'RPAREN', func_call]],
    [vasign_func_call, 'RPAREN', None],
    [vasign_func_call, 'LBRACE', None],
    [vasign_func_call, 'RBRACE', None],
    [vasign_func_call, 'READ', None],
    [vasign_func_call, 'QUOTES', None],
    [vasign_func_call, 'WRITE', None],
    [vasign_func_call, 'BOOL', None],
    [vasign_func_call, 'LOGIC', None],
    [vasign_func_call, 'ASSIGN', [aux_add_dec]],
    [vasign_func_call, 'INT', None],
    [vasign_func_call, 'FLOAT', None],
    [vasign_func_call, 'CHAR', None],
    [vasign_func_call, 'RELATIONAL', None],
    [vasign_func_call, 'OP', ['OP', 'OP']],
    [vasign_func_call, 'MOD', None],
    [vasign_func_call, 'ID', None],
    [vasign_func_call, 'STRING', None],
    [vasign_func_call, 'NUMBER', None],
    [vasign_func_call, 'IF',None ],
    [vasign_func_call, 'ELSE', None],
    [vasign_func_call, 'EOF', None],

    [func_call_or_dec, 'SEMICOLON', [func_call]],
    [func_call_or_dec, 'COMMA', None],
    [func_call_or_dec, 'WHILE', None],
    [func_call_or_dec, 'LPAREN', None],
    [func_call_or_dec, 'RPAREN', None],
    [func_call_or_dec, 'LBRACE', ['LBRACE', func_instruction, 'RBRACE']],
    [func_call_or_dec, 'RBRACE', None],
    [func_call_or_dec, 'READ', None],
    [func_call_or_dec, 'QUOTES', None],
    [func_call_or_dec, 'WRITE', None],
    [func_call_or_dec, 'BOOL', None],
    [func_call_or_dec, 'LOGIC', None],
    [func_call_or_dec, 'ASSIGN', None],
    [func_call_or_dec, 'INT', None],
    [func_call_or_dec, 'FLOAT', None],
    [func_call_or_dec, 'CHAR', None],
    [func_call_or_dec, 'RELATIONAL', None],
    [func_call_or_dec, 'OP', None],
    [func_call_or_dec, 'MOD', None],
    [func_call_or_dec, 'ID', None],
    [func_call_or_dec, 'STRING', None],
    [func_call_or_dec, 'NUMBER', None],
    [func_call_or_dec, 'IF',None ],
    [func_call_or_dec, 'ELSE', None],
    [func_call_or_dec, 'EOF', None],

    [func_call, 'SEMICOLON', ['empty']],
    [func_call, 'COMMA', None],
    [func_call, 'WHILE', None],
    [func_call, 'LPAREN', None],
    [func_call, 'RPAREN', None],
    [func_call, 'LBRACE', None],
    [func_call, 'RBRACE', None],
    [func_call, 'READ', None],
    [func_call, 'QUOTES', None],
    [func_call, 'WRITE', None],
    [func_call, 'BOOL', None],
    [func_call, 'LOGIC', None],
    [func_call, 'ASSIGN', None],
    [func_call, 'INT', None],
    [func_call, 'FLOAT', None],
    [func_call, 'CHAR', None],
    [func_call, 'RELATIONAL', None],
    [func_call, 'OP', None],
    [func_call, 'MOD', None],
    [func_call, 'ID', None],
    [func_call, 'STRING', None],
    [func_call, 'NUMBER', None],
    [func_call, 'IF',None ],
    [func_call, 'ELSE', None],
    [func_call, 'EOF', None],

    # 2
    [func_or_var_dec, 'SEMICOLON', None],
    [func_or_var_dec, 'COMMA', None],
    [func_or_var_dec, 'WHILE', None],
    [func_or_var_dec, 'LPAREN', None],
    [func_or_var_dec, 'RPAREN', None],
    [func_or_var_dec, 'LBRACE', None],
    [func_or_var_dec, 'RBRACE', None],
    [func_or_var_dec, 'READ', None],
    [func_or_var_dec, 'QUOTES', None],
    [func_or_var_dec, 'WRITE', None],
    [func_or_var_dec, 'BOOL', None],
    [func_or_var_dec, 'LOGIC', None],
    [func_or_var_dec, 'ASSIGN', None],
    [func_or_var_dec, 'INT', [datatype, aux_func_or_var_dec]],
    [func_or_var_dec, 'FLOAT', [datatype, aux_func_or_var_dec]],
    [func_or_var_dec, 'CHAR', [datatype, aux_func_or_var_dec]],
    [func_or_var_dec, 'RELATIONAL', None],
    [func_or_var_dec, 'OP', None],
    [func_or_var_dec, 'MOD', None],
    [func_or_var_dec, 'ID', None],
    [func_or_var_dec, 'STRING', None],
    [func_or_var_dec, 'NUMBER', None],
    [func_or_var_dec, 'IF',None ],
    [func_or_var_dec, 'ELSE', None],
    [func_or_var_dec, 'EOF', None],
    # 3
    [aux_func_or_var_dec, 'SEMICOLON', None ],
    [aux_func_or_var_dec,  'COMMA', None ],
    [aux_func_or_var_dec, 'WHILE', None ],
    [aux_func_or_var_dec, 'LPAREN', None],
    [aux_func_or_var_dec, 'RPAREN', None ],
    [aux_func_or_var_dec, 'LBRACE', None ],
    [aux_func_or_var_dec, 'RBRACE', None ],
    [aux_func_or_var_dec, 'READ', None ],
    [aux_func_or_var_dec, 'QUOTES', None ],
    [aux_func_or_var_dec, 'WRITE', None ],
    [aux_func_or_var_dec, 'BOOL', None ],
    [aux_func_or_var_dec, 'LOGIC', None ],
    [aux_func_or_var_dec, 'ASSIGN', None ],
    [aux_func_or_var_dec, 'INT', None ],
    [aux_func_or_var_dec, 'FLOAT', None ],
    [aux_func_or_var_dec, 'CHAR', None ],
    [aux_func_or_var_dec, 'RELATIONAL', None ],
    [aux_func_or_var_dec, 'OP', None ],
    [aux_func_or_var_dec, 'MOD', None ],
    [aux_func_or_var_dec, 'ID', ['ID', aux_var_asign]],
    [aux_func_or_var_dec, 'STRING', None ],
    [aux_func_or_var_dec, 'NUMBER', None],
    [aux_func_or_var_dec, 'IF',None ],
    [aux_func_or_var_dec, 'ELSE', None],
    [aux_func_or_var_dec, 'EOF', None],
    #4
    [aux_add_dec, 'SEMICOLON', ['empty']],
    [aux_add_dec, 'COMMA', ['COMMA', 'ID', aux_add_dec]],
    [aux_add_dec, 'WHILE', None],
    [aux_add_dec, 'LPAREN', None],
    [aux_add_dec, 'RPAREN', None],
    [aux_add_dec, 'LBRACE', None],
    [aux_add_dec, 'RBRACE', None],
    [aux_add_dec, 'READ', None],
    [aux_add_dec, 'QUOTES', None],
    [aux_add_dec, 'WRITE', None],
    [aux_add_dec, 'BOOL', None],
    [aux_add_dec, 'LOGIC', None],
    [aux_add_dec, 'ASSIGN', ['ASSIGN', data, aux_add_dec]],
    [aux_add_dec, 'INT', None],
    [aux_add_dec, 'FLOAT', None],
    [aux_add_dec, 'CHAR', None],
    [aux_add_dec, 'RELATIONAL', None],
    [aux_add_dec, 'OP', None],
    [aux_add_dec, 'MOD', None],
    [aux_add_dec, 'ID', None],
    [aux_add_dec, 'STRING', None],
    [aux_add_dec, 'NUMBER', None],
    [aux_add_dec, 'IF',None ],
    [aux_add_dec, 'ELSE', None],
    [aux_add_dec, 'EOF', None],
    #5
    [aux_var_asign, 'SEMICOLON', ['SEMICOLON']],
    [aux_var_asign, 'COMMA', [aux_add_dec, 'SEMICOLON']],
    [aux_var_asign, 'WHILE', None],
    [aux_var_asign, 'LPAREN', ['LPAREN', func_call_or_dec_aux]],
    [aux_var_asign, 'RPAREN', None],
    [aux_var_asign, 'LBRACE', None],
    [aux_var_asign, 'RBRACE', None],
    [aux_var_asign, 'READ', None],
    [aux_var_asign, 'QUOTES', None],
    [aux_var_asign, 'WRITE', None],
    [aux_var_asign, 'BOOL', None],
    [aux_var_asign, 'LOGIC', None],
    [aux_var_asign, 'ASSIGN', [aux_add_dec, 'SEMICOLON']],
    [aux_var_asign, 'INT', None],
    [aux_var_asign, 'FLOAT',None],
    [aux_var_asign, 'CHAR', None],
    [aux_var_asign, 'RELATIONAL', None],
    [aux_var_asign, 'OP', None],
    [aux_var_asign, 'MOD', None],
    [aux_var_asign, 'ID', None],
    [aux_var_asign, 'STRING', None],
    [aux_var_asign, 'NUMBER', None],
    [aux_var_asign, 'IF',None ],
    [aux_var_asign, 'ELSE', None],
    [aux_var_asign, 'EOF', None],
    #6
    [while_op, 'SEMICOLON', None],
    [while_op, 'COMMA', None],
    [while_op, 'WHILE', ['WHILE','LPAREN' , conditions, 'RPAREN' , 'LBRACE', func_instruction, 'RBRACE']],
    [while_op, 'LPAREN', None],
    [while_op, 'RPAREN', None],
    [while_op, 'LBRACE', None],
    [while_op, 'RBRACE', None],
    [while_op, 'READ', None],
    [while_op, 'QUOTES',None],
    [while_op, 'WRITE', None],
    [while_op, 'BOOL',None ],
    [while_op, 'LOGIC', None],
    [while_op, 'ASSIGN', None],
    [while_op, 'INT',None ],
    [while_op, 'FLOAT',None ],
    [while_op, 'CHAR',None ],
    [while_op, 'RELATIONAL',None ],
    [while_op, 'OP', None],
    [while_op, 'MOD',None ],
    [while_op, 'ID', None],
    [while_op, 'STRING', None],
    [while_op, 'NUMBER', None],
    [while_op, 'IF',None ],
    [while_op, 'ELSE', None],
    [while_op, 'EOF', None],
    #7
    [conditions, 'SEMICOLON', None],
    [conditions, 'COMMA', None],
    [conditions, 'WHILE', None],
    [conditions, 'LPAREN', None],
    [conditions, 'RPAREN', None],
    [conditions, 'LBRACE', None],
    [conditions, 'RBRACE', None],
    [conditions, 'READ', None],
    [conditions, 'QUOTES', None],
    [conditions, 'WRITE', None],
    [conditions, 'BOOL', [bool_logic, bool_logic_conn]],
    [conditions, 'LOGIC', None],
    [conditions, 'ASSIGN', None],
    [conditions, 'INT', None],
    [conditions, 'FLOAT', None],
    [conditions, 'CHAR', None],
    [conditions, 'RELATIONAL', None],
    [conditions, 'OP', None],
    [conditions, 'MOD', None],
    [conditions, 'ID', [bool_logic, bool_logic_conn]],
    [conditions, 'STRING', None],
    [conditions, 'NUMBER', None],
    [conditions, 'IF',None ],
    [conditions, 'ELSE', None],
    [conditions, 'EOF', None],
    #8
    [bool_logic_conn, 'SEMICOLON', None],
    [bool_logic_conn, 'COMMA', None],
    [bool_logic_conn, 'WHILE', None],
    [bool_logic_conn, 'LPAREN', None],
    [bool_logic_conn, 'RPAREN', ['empty']],
    [bool_logic_conn, 'LBRACE', None],
    [bool_logic_conn, 'RBRACE', None],
    [bool_logic_conn, 'READ', None],
    [bool_logic_conn, 'QUOTES', None],
    [bool_logic_conn, 'WRITE', None],
    [bool_logic_conn, 'BOOL', None],
    [bool_logic_conn, 'LOGIC', None],
    [bool_logic_conn, 'ASSIGN', None],
    [bool_logic_conn, 'INT', None],
    [bool_logic_conn, 'FLOAT', None],
    [bool_logic_conn, 'CHAR', None],
    [bool_logic_conn, 'RELATIONAL', ['RELATIONAL', bool_logic, bool_logic_conn]],
    [bool_logic_conn, 'OP', None],
    [bool_logic_conn, 'MOD', None],
    [bool_logic_conn, 'ID', None],
    [bool_logic_conn, 'STRING', None],
    [bool_logic_conn, 'NUMBER', None],
    [bool_logic_conn, 'IF',None ],
    [bool_logic_conn, 'ELSE', None],
    [bool_logic_conn, 'EOF', None],
    #9
    [bool_logic, 'SEMICOLON', None],
    [bool_logic, 'COMMA', None],
    [bool_logic, 'WHILE', None],
    [bool_logic, 'LPAREN', None],
    [bool_logic, 'RPAREN', None],
    [bool_logic, 'LBRACE', None],
    [bool_logic, 'RBRACE', None],
    [bool_logic, 'READ', None],
    [bool_logic, 'QUOTES', None],
    [bool_logic, 'WRITE', None],
    [bool_logic, 'BOOL', ['BOOL']],
    [bool_logic, 'LOGIC', None],
    [bool_logic, 'ASSIGN', None],
    [bool_logic, 'INT', None],
    [bool_logic, 'FLOAT', None],
    [bool_logic, 'CHAR', None],
    [bool_logic, 'RELATIONAL', None],
    [bool_logic, 'OP', None],
    [bool_logic, 'MOD', None],
    [bool_logic, 'ID', ['ID', logic_conn]],
    [bool_logic, 'STRING', None],
    [bool_logic, 'NUMBER', ['NUMBER', logic_conn]],
    [bool_logic, 'EOF', None],
    #10
    [logic_conn, 'SEMICOLON', None],
    [logic_conn, 'COMMA', None],
    [logic_conn, 'WHILE', None],
    [logic_conn, 'LPAREN', None],
    [logic_conn, 'RPAREN', ['empty']],
    [logic_conn, 'LBRACE', None],
    [logic_conn, 'RBRACE', None],
    [logic_conn, 'READ', None],
    [logic_conn, 'QUOTES', None],
    [logic_conn, 'WRITE', None],
    [logic_conn, 'BOOL', None],
    [logic_conn, 'LOGIC', ['LOGIC' , 'ID']],
    [logic_conn, 'ASSIGN', None],
    [logic_conn, 'INT', None],
    [logic_conn, 'FLOAT', None],
    [logic_conn, 'CHAR', None],
    [logic_conn, 'RELATIONAL', ['empty']],
    [logic_conn, 'OP', None],
    [logic_conn, 'MOD', None],
    [logic_conn, 'ID', ['ID']],
    [logic_conn, 'STRING', None],
    [logic_conn, 'NUMBER', ['NUMBER']],
    [logic_conn, 'IF',None ],
    [logic_conn, 'ELSE', None],
    [logic_conn, 'EOF', None],
    #11
    [operation, 'SEMICOLON',None ],
    [operation, 'COMMA',None ],
    [operation, 'WHILE',None ],
    [operation, 'LPAREN', None],
    [operation, 'RPAREN', None],
    [operation, 'LBRACE', None],
    [operation, 'RBRACE', None],
    [operation, 'READ', None],
    [operation, 'QUOTES', None],
    [operation, 'WRITE', None],
    [operation, 'BOOL', None],
    [operation, 'LOGIC', None],
    [operation, 'ASSIGN', None],
    [operation, 'INT',None ],
    [operation, 'FLOAT',None ],
    [operation, 'CHAR',None ],
    [operation, 'RELATIONAL',None ],
    [operation, 'OP', None],
    [operation, 'MOD',None ],
    [operation, 'ID', ['ID','OP','ID',aux_operation]],
    [operation, 'STRING', None],
    [operation, 'NUMBER', None],
    [operation, 'IF',None ],
    [operation, 'ELSE', None],
    [operation, 'EOF', None],
    #12
    [aux_operation, 'SEMICOLON', ['empty']],
    [aux_operation, 'COMMA', ['empty']],
    [aux_operation, 'WHILE', None],
    [aux_operation, 'LPAREN', None],
    [aux_operation, 'RPAREN', None],
    [aux_operation, 'LBRACE', None],
    [aux_operation, 'RBRACE', None],
    [aux_operation, 'READ', None],
    [aux_operation, 'QUOTES', None],
    [aux_operation, 'WRITE', None],
    [aux_operation, 'BOOL', None],
    [aux_operation, 'LOGIC', None],
    [aux_operation, 'ASSIGN', None],
    [aux_operation, 'INT', None],
    [aux_operation, 'FLOAT', None],
    [aux_operation, 'CHAR', None],
    [aux_operation, 'RELATIONAL', None],
    [aux_operation, 'OP', ['OP', 'ID', aux_operation]],
    [aux_operation, 'MOD', None],
    [aux_operation, 'ID', None],
    [aux_operation, 'STRING', None],
    [aux_operation, 'NUMBER', None],
    [aux_operation, 'IF',None ],
    [aux_operation, 'ELSE', None],
    [aux_operation, 'EOF', None],
    #13
    [scanf, 'SEMICOLON', None],
    [scanf, 'COMMA', None],
    [scanf, 'WHILE', None],
    [scanf, 'LPAREN', None],
    [scanf, 'RPAREN', None],
    [scanf, 'LBRACE', None],
    [scanf, 'RBRACE', None],
    [scanf, 'READ', ['READ', 'LPAREN', 'STRING', 'COMMA', add_ids, 'RPAREN']],
    [scanf, 'QUOTES', None],
    [scanf, 'WRITE', None],
    [scanf, 'BOOL', None],
    [scanf, 'LOGIC', None],
    [scanf, 'ASSIGN', None],
    [scanf, 'INT', None],
    [scanf, 'FLOAT', None],
    [scanf, 'CHAR', None],
    [scanf, 'RELATIONAL', None],
    [scanf, 'OP', None],
    [scanf, 'MOD', None],
    [scanf, 'ID', None],
    [scanf, 'STRING', None],
    [scanf, 'NUMBER', None],
    [scanf, 'IF',None ],
    [scanf, 'ELSE', None],
    [scanf, 'EOF', None],
    #14
    [printf, 'SEMICOLON', None],
    [printf, 'COMMA', None],
    [printf, 'WHILE', None],
    [printf, 'LPAREN', None],
    [printf, 'RPAREN', None],
    [printf, 'LBRACE', None],
    [printf, 'RBRACE', None],
    [printf, 'READ', None],
    [printf, 'QUOTES',None ],
    [printf, 'WRITE', ['WRITE', 'LPAREN','STRING', aux_printf,'RPAREN']],
    [printf, 'BOOL',None ],
    [printf, 'LOGIC', None],
    [printf, 'ASSIGN', None],
    [printf, 'INT',None ],
    [printf, 'FLOAT',None ],
    [printf, 'CHAR',None ],
    [printf, 'RELATIONAL',None ],
    [printf, 'OP', None],
    [printf, 'MOD',None ],
    [printf, 'ID', None],
    [printf, 'STRING', None],
    [printf, 'NUMBER', None],
    [printf, 'IF',None ],
    [printf, 'ELSE', None],
    [printf, 'EOF', None],
    #15
    [aux_printf, 'SEMICOLON', None],
    [aux_printf, 'COMMA', ['COMMA', add_ids]],
    [aux_printf, 'WHILE', None],
    [aux_printf, 'LPAREN', None],
    [aux_printf, 'RPAREN', ['empty']],
    [aux_printf, 'LBRACE', None],
    [aux_printf, 'RBRACE', None],
    [aux_printf, 'READ', None],
    [aux_printf, 'QUOTES', None],
    [aux_printf, 'WRITE', None],
    [aux_printf, 'BOOL', None],
    [aux_printf, 'LOGIC', None],
    [aux_printf, 'ASSIGN', None],
    [aux_printf, 'INT', None],
    [aux_printf, 'FLOAT', None],
    [aux_printf, 'CHAR', None],
    [aux_printf, 'RELATIONAL', None],
    [aux_printf, 'OP', None],
    [aux_printf, 'MOD', None],
    [aux_printf, 'ID', None],
    [aux_printf, 'STRING', None],
    [aux_printf, 'NUMBER', None],
    [aux_printf, 'IF',None ],
    [aux_printf, 'ELSE', None],
    [aux_printf, 'EOF', None],
    #16
    [add_mods, 'SEMICOLON', None],
    [add_mods, 'COMMA', None],
    [add_mods, 'WHILE', None],
    [add_mods, 'LPAREN', None],
    [add_mods, 'RPAREN', None],
    [add_mods, 'LBRACE', None],
    [add_mods, 'RBRACE', None],
    [add_mods, 'READ', None],
    [add_mods, 'QUOTES', None],
    [add_mods, 'WRITE', None],
    [add_mods, 'BOOL', None],
    [add_mods, 'LOGIC', None],
    [add_mods, 'ASSIGN', None],
    [add_mods, 'INT', None],
    [add_mods, 'FLOAT', None],
    [add_mods, 'CHAR', None],
    [add_mods, 'RELATIONAL', None],
    [add_mods, 'OP', None],
    [add_mods, 'MOD', ['MOD', aux_mods]],
    [add_mods, 'ID', None],
    [add_mods, 'STRING', None],
    [add_mods, 'NUMBER', None],
    [add_mods, 'IF',None ],
    [add_mods, 'ELSE', None],
    [add_mods, 'EOF', None],
    #17
    [aux_mods, 'SEMICOLON', None],
    [aux_mods, 'COMMA', None],
    [aux_mods, 'WHILE', None],
    [aux_mods, 'LPAREN', None],
    [aux_mods, 'RPAREN', None],
    [aux_mods, 'LBRACE', None],
    [aux_mods, 'RBRACE', None],
    [aux_mods, 'READ', None],
    [aux_mods, 'QUOTES', ['empty']],
    [aux_mods, 'WRITE', None],
    [aux_mods, 'BOOL', None],
    [aux_mods, 'LOGIC', None],
    [aux_mods, 'ASSIGN', None],
    [aux_mods, 'INT', None],
    [aux_mods, 'FLOAT', None],
    [aux_mods, 'CHAR', None],
    [aux_mods, 'RELATIONAL', None],
    [aux_mods, 'OP', None],
    [aux_mods, 'MOD', ['MOD', aux_mods]],
    [aux_mods, 'ID', None],
    [aux_mods, 'STRING', None],
    [aux_mods, 'NUMBER', None],
    [aux_mods, 'IF',None ],
    [aux_mods, 'ELSE', None],
    [aux_mods, 'EOF', None],
    #18
    [add_ids, 'SEMICOLON', None],
    [add_ids, 'COMMA', None],
    [add_ids, 'WHILE', None],
    [add_ids, 'LPAREN', None],
    [add_ids, 'RPAREN', None],
    [add_ids, 'LBRACE', None],
    [add_ids, 'RBRACE', None],
    [add_ids, 'READ', None],
    [add_ids, 'QUOTES', None],
    [add_ids, 'WRITE', None],
    [add_ids, 'BOOL', None],
    [add_ids, 'LOGIC', None],
    [add_ids, 'ASSIGN', None],
    [add_ids, 'INT', None],
    [add_ids, 'FLOAT', None],
    [add_ids, 'CHAR', None],
    [add_ids, 'RELATIONAL', None],
    [add_ids, 'OP', None],
    [add_ids, 'MOD', None],
    [add_ids, 'ID', ['ID', aux_ids]],
    [add_ids, 'STRING', None],
    [add_ids, 'NUMBER', None],
    [add_ids, 'IF',None ],
    [add_ids, 'ELSE', None],
    [add_ids, 'EOF', None],
    #19
    [aux_ids, 'SEMICOLON',None ],
    [aux_ids, 'COMMA',['COMMA','ID',aux_ids] ],
    [aux_ids, 'WHILE',None ],
    [aux_ids, 'LPAREN', None],
    [aux_ids, 'RPAREN', ['empty']],
    [aux_ids, 'LBRACE', None],
    [aux_ids, 'RBRACE', None],
    [aux_ids, 'READ', None],
    [aux_ids, 'QUOTES', None],
    [aux_ids, 'WRITE', None],
    [aux_ids, 'BOOL', None],
    [aux_ids, 'LOGIC', None],
    [aux_ids, 'ASSIGN', None],
    [aux_ids, 'INT',None ],
    [aux_ids, 'FLOAT',None ],
    [aux_ids, 'CHAR',None ],
    [aux_ids, 'RELATIONAL',None ],
    [aux_ids, 'OP', None],
    [aux_ids, 'MOD',None ],
    [aux_ids, 'ID', None],
    [aux_ids, 'STRING', None],
    [aux_ids, 'NUMBER', None],
    [aux_ids, 'IF',None ],
    [aux_ids, 'ELSE', None],
    [aux_ids, 'EOF', None],
    #20
    [datatype, 'SEMICOLON', None],
    [datatype, 'COMMA', None],
    [datatype, 'WHILE', None],
    [datatype, 'LPAREN', None],
    [datatype, 'RPAREN', None],
    [datatype, 'LBRACE', None],
    [datatype, 'RBRACE', None],
    [datatype, 'READ', None],
    [datatype, 'QUOTES', None],
    [datatype, 'WRITE', None],
    [datatype, 'BOOL', None],
    [datatype, 'LOGIC', None],
    [datatype, 'ASSIGN', None],
    [datatype, 'INT', ['INT']],
    [datatype, 'FLOAT', ['FLOAT']],
    [datatype, 'CHAR', ['CHAR']],
    [datatype, 'RELATIONAL', None],
    [datatype, 'OP', None],
    [datatype, 'MOD', None],
    [datatype, 'ID', None],
    [datatype, 'STRING', None],
    [datatype, 'NUMBER', None],
    [datatype, 'IF',None ],
    [datatype, 'ELSE', None],
    [datatype, 'EOF', None],
    #21
    [data, 'SEMICOLON', None],
    [data, 'COMMA', None],
    [data, 'WHILE', None],
    [data, 'LPAREN', None],
    [data, 'RPAREN', None],
    [data, 'LBRACE', None],
    [data, 'RBRACE', None],
    [data, 'READ', None],
    [data, 'QUOTES', None],
    [data, 'WRITE', None],
    [data, 'BOOL', None],
    [data, 'LOGIC', None],
    [data, 'ASSIGN', None],
    [data, 'INT', None],
    [data, 'FLOAT', None],
    [data, 'CHAR', None],
    [data, 'RELATIONAL', None],
    [data, 'OP', None],
    [data, 'MOD', None],
    [data, 'ID', [operation]],
    [data, 'STRING', ['STRING']],
    [data, 'NUMBER', ['NUMBER']],
    [data, 'IF',None ],
    [data, 'ELSE', None],
    [data, 'EOF', None],

    [if_else, 'SEMICOLON', None],
    [if_else, 'COMMA', None],
    [if_else, 'WHILE', None],
    [if_else, 'LPAREN', None],
    [if_else, 'RPAREN', None],
    [if_else, 'LBRACE', None],
    [if_else, 'RBRACE', None],
    [if_else, 'READ', None],
    [if_else, 'QUOTES',None],
    [if_else, 'WRITE', None],
    [if_else, 'BOOL',None ],
    [if_else, 'LOGIC', None],
    [if_else, 'ASSIGN', None],
    [if_else, 'INT',None ],
    [if_else, 'FLOAT',None ],
    [if_else, 'CHAR',None ],
    [if_else, 'RELATIONAL',None ],
    [if_else, 'OP', None],
    [if_else, 'MOD',None ],
    [if_else, 'ID', None],
    [if_else, 'STRING', None],
    [if_else, 'NUMBER', None],
    [if_else, 'IF',[if_dec]],
    [if_else, 'ELSE', [else_dec]],
    [if_else, 'EOF', None],

    [if_dec, 'SEMICOLON', None],
    [if_dec, 'COMMA', None],
    [if_dec, 'WHILE', None],
    [if_dec, 'LPAREN', None],
    [if_dec, 'RPAREN', None],
    [if_dec, 'LBRACE', None],
    [if_dec, 'RBRACE', None],
    [if_dec, 'READ', None],
    [if_dec, 'QUOTES',None],
    [if_dec, 'WRITE', None],
    [if_dec, 'BOOL',None ],
    [if_dec, 'LOGIC', None],
    [if_dec, 'ASSIGN', None],
    [if_dec, 'INT',None ],
    [if_dec, 'FLOAT',None ],
    [if_dec, 'CHAR',None ],
    [if_dec, 'RELATIONAL',None ],
    [if_dec, 'OP', None],
    [if_dec, 'MOD',None ],
    [if_dec, 'ID', None],
    [if_dec, 'STRING', None],
    [if_dec, 'NUMBER', None],
    [if_dec, 'IF', [ 'IF', 'LPAREN', ifelse_conditions, 'RPAREN', 'LBRACE', func_instruction, 'RBRACE'] ],
    [if_dec, 'ELSE', None],
    [if_dec, 'EOF', None],

    [else_dec, 'SEMICOLON', None],
    [else_dec, 'COMMA', None],
    [else_dec, 'WHILE', None],
    [else_dec, 'LPAREN', None],
    [else_dec, 'RPAREN', None],
    [else_dec, 'LBRACE', None],
    [else_dec, 'RBRACE', None],
    [else_dec, 'READ', None],
    [else_dec, 'QUOTES',None],
    [else_dec, 'WRITE', None],
    [else_dec, 'BOOL',None ],
    [else_dec, 'LOGIC', None],
    [else_dec, 'ASSIGN', None],
    [else_dec, 'INT',None ],
    [else_dec, 'FLOAT',None ],
    [else_dec, 'CHAR',None ],
    [else_dec, 'RELATIONAL',None ],
    [else_dec, 'OP', None],
    [else_dec, 'MOD',None ],
    [else_dec, 'ID', None],
    [else_dec, 'IF',None ],
    [else_dec, 'ELSE', ['ELSE', 'LBRACE', func_instruction, 'RBRACE']],
    [else_dec, 'EOF', None],

    [ifelse_bool, 'SEMICOLON', None],
    [ifelse_bool, 'COMMA', None],
    [ifelse_bool, 'WHILE', None],
    [ifelse_bool, 'LPAREN', None],
    [ifelse_bool, 'RPAREN', None],
    [ifelse_bool, 'LBRACE', None],
    [ifelse_bool, 'RBRACE', None],
    [ifelse_bool, 'READ', None],
    [ifelse_bool, 'QUOTES', None],
    [ifelse_bool, 'WRITE', None],
    [ifelse_bool, 'BOOL', ['BOOL']],
    [ifelse_bool, 'LOGIC', None],
    [ifelse_bool, 'ASSIGN', None],
    [ifelse_bool, 'INT', None],
    [ifelse_bool, 'FLOAT', None],
    [ifelse_bool, 'CHAR', None],
    [ifelse_bool, 'RELATIONAL', None],
    [ifelse_bool, 'OP', None],
    [ifelse_bool, 'MOD', None],
    [ifelse_bool, 'ID', ['ID', 'LOGIC', logic_conn]],
    [ifelse_bool, 'STRING', None],
    [ifelse_bool, 'NUMBER', ['NUMBER', 'LOGIC', logic_conn]],
    [ifelse_bool, 'EOF', None],

    [ifelse_conditions, 'SEMICOLON', None],
    [ifelse_conditions, 'COMMA', None],
    [ifelse_conditions, 'WHILE', None],
    [ifelse_conditions, 'LPAREN', None],
    [ifelse_conditions, 'RPAREN', None],
    [ifelse_conditions, 'LBRACE', None],
    [ifelse_conditions, 'RBRACE', None],
    [ifelse_conditions, 'READ', None],
    [ifelse_conditions, 'QUOTES', None],
    [ifelse_conditions, 'WRITE', None],
    [ifelse_conditions, 'BOOL', [ifelse_bool, ifelse_bool_logic_conn]],
    [ifelse_conditions, 'LOGIC', None],
    [ifelse_conditions, 'ASSIGN', None],
    [ifelse_conditions, 'INT', None],
    [ifelse_conditions, 'FLOAT', None],
    [ifelse_conditions, 'CHAR', None],
    [ifelse_conditions, 'RELATIONAL', None],
    [ifelse_conditions, 'OP', None],
    [ifelse_conditions, 'MOD', None],
    [ifelse_conditions, 'ID', [ifelse_bool, ifelse_bool_logic_conn]],
    [ifelse_conditions, 'STRING', None],
    [ifelse_conditions, 'NUMBER', None],
    [ifelse_conditions, 'IF',None ],
    [ifelse_conditions, 'ELSE', None],
    [ifelse_conditions, 'EOF', None],

    [ifelse_bool_logic_conn, 'SEMICOLON', None],
    [ifelse_bool_logic_conn, 'COMMA', None],
    [ifelse_bool_logic_conn, 'WHILE', None],
    [ifelse_bool_logic_conn, 'LPAREN', None],
    [ifelse_bool_logic_conn, 'RPAREN', ['empty']],
    [ifelse_bool_logic_conn, 'LBRACE', None],
    [ifelse_bool_logic_conn, 'RBRACE', None],
    [ifelse_bool_logic_conn, 'READ', None],
    [ifelse_bool_logic_conn, 'QUOTES', None],
    [ifelse_bool_logic_conn, 'WRITE', None],
    [ifelse_bool_logic_conn, 'BOOL', None],
    [ifelse_bool_logic_conn, 'LOGIC', None],
    [ifelse_bool_logic_conn, 'ASSIGN', None],
    [ifelse_bool_logic_conn, 'INT', None],
    [ifelse_bool_logic_conn, 'FLOAT', None],
    [ifelse_bool_logic_conn, 'CHAR', None],
    [ifelse_bool_logic_conn, 'RELATIONAL', ['RELATIONAL', ifelse_bool_logic, ifelse_bool_logic_conn]],
    [ifelse_bool_logic_conn, 'OP', None],
    [ifelse_bool_logic_conn, 'MOD', None],
    [ifelse_bool_logic_conn, 'ID', None],
    [ifelse_bool_logic_conn, 'STRING', None],
    [ifelse_bool_logic_conn, 'NUMBER', None],
    [ifelse_bool_logic_conn, 'IF',None ],
    [ifelse_bool_logic_conn, 'ELSE', None],
    [ifelse_bool_logic_conn, 'EOF', None],
]
